### ISSUE TITLE
Not able to show "Underline, Subscript, Superscript" Option 

### ISSUE THREAD

**Issue by Ashubgs90** [waynestate/nova-ckeditor4-field#11]
I am not able to show `Underline, Subscript, Superscript` Option in Nova

I tried to remove these options form config.js 
`config.removeButtons = 'Underline,Subscript,Superscript';`

But still was not able to get desire result.

**Comment by Ashubgs90** [comment]
NO Update yet 👎

**Comment by chrispelzer** [comment]
What is the location of the `config.js` file you are editing?

If you wish to pass custom config options to the CKEditor you can do so by [publishing the package's configuration file](https://github.com/waynestate/nova-ckeditor4-field#overriding-config-values) and then [customizing the `toolbar` option](https://github.com/waynestate/nova-ckeditor4-field#customization). Which you'll be able to remove the Underline, Subscript, and Superscript from.

**Comment by Ashubgs90** [comment]
I am using backpack admin panel currently and migrating it Nova. And I have publishing the package's configuration file and then customizing the toolbar option... But haven't got `Underline, Subscript, Superscript` option.

**Comment by chrispelzer** [comment]
I see what you mean. It looks like the `Underline, Subscript, and Superscript` buttons are part of the Full CKEditor Preset instead of the Standard.

If you replace within the published `config/nova/ckeditor-field.php` the key for `ckeditor_url` with `https://cdn.ckeditor.com/4.10.1/full-all/ckeditor.js`, it should now pull in the buttons, which can be removed with the `removeButtons`.

**Comment by Ashubgs90** [comment]
yes... it resolved the issue. 
Thanks
