### ISSUE TITLE
What about setting CKEDITOR.dtd ?

### ISSUE THREAD

**Issue by Askar-Rymbayev** [waynestate/nova-ckeditor4-field#25]
I am about solved question on [this page](https://stackoverflow.com/questions/18250404/ckeditor-strips-i-tag)

Editor strips `<i>` tag
I tried this

```
CKEditor::make('text')->options([
                'allowedContent' => true,
                'extraAllowedContent' => 'i;u;style;span;ul;li;table;td;style;*[id];*(*);*{*}',
                'coreStyles_italic' => [
                    'element' => 'i',
                    'overrides' => 'em'
                ],
                'removeButtons' => 'Cut,Copy,Paste,Undo,Redo,Anchor',
            ])
```

but it does not work

**Comment by chrispelzer** [comment]
This would require overriding the core configurations for CKEditor which isn't possible through the CKEditor options.

You'd need your own "configuration" to override the CKEditor object.

It's similar to what is done when wanting to add extra plugins that are not part of the CKEditor default plugin list: https://github.com/waynestate/nova-ckeditor4-field/wiki/Adding-additional-plugins

Since you wish to just override the configuration and not add a plugin, you'll need to follow steps 3 and 4.
